---
flask_apps:
  - name: hello
    domain: hello.test
    repository: https://github.com/e-lie/flask_hello_ansible.git
    version: master
    user: flask1

  - name: hello2
    domain: hello2.test
    repository: https://github.com/e-lie/flask_hello_ansible.git
    version: master
    user: flask2



 